version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_DATABASE=postgresDB
      - POSTGRES_PASSWORD=teste999
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local